name = "dnukha-server"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "birthday_db"
database_id = "f8ebfe41-968f-4761-9df8-85cb767089b1"

[vars]
OPENROUTER_MODEL_PRIMARY  = "meta-llama/llama-3.1-8b-instruct:free"
OPENROUTER_MODEL_FALLBACK = "google/gemma-2-9b-it:free"
HETZNER_URL = "https://xn----7sbaf8bgxj5a.xn--p1ai:8443"

[triggers]
crons = ["*/30 * * * *"]
